version: "3.7"

services:
  vikranportfolio:
    image: registry.hunvikran.com/nobay/sokhonportfolio
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.sokhonportfolio-http.rule=Host(`chhunsokhon.com`)||Host(`www.chhunsokhon.com`)
      - traefik.http.routers.sokhonportfolio-http.entrypoints=http
      - traefik.http.routers.sokhonportfolio-http.middlewares=redirect,sokhonportfolio-redirect
      - traefik.http.routers.sokhonportfolio-https.rule=Host(`chhunsokhon.com`)||Host(`www.chhunsokhon.com`)
      - traefik.http.routers.sokhonportfolio-https.entrypoints=https
      - traefik.http.routers.sokhonportfolio-https.middlewares=sokhonportfolio-redirect
      - treafik.http.middlewares.sokhonportfolio-redirect.redirectregex.regex=^(https?://)www.(.*)$$
      - traefik.http.middlewares.sokhonportfolio-redirect.redirectregex.replacement=$${1}$${2}
      - traefik.http.routers.sokhonportfolio-https.tls=true
      - traefik.http.routers.sokhonportfolio-https.tls.certresolver=letsencrypt
      - traefik.http.services.sokhonportfolio.loadbalancer.server.port=80
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    driver: overlay
    external: true
    attachable: true